#!/bin/csh -f
#version calls an new qsub
set count = $1
set last = $2
set beta = $3
set beta_a = $4
set mass = $5
set binary = $6
set ns = $7
set nt = $8
set label = $9
set low = $10

#  We will copy everything big to $BATCH_TMPDIR

limit core 0

set mynode = ` hostname -s `





set kind = ${ns}${nt}_${beta}_${mass}_${label}

set exec_dir = /nfs/beowulf02/anna2/KSNHYP/FA-ks481216
set home_dir = /amd/huron/axp/huron/wrk1/ltm/gregpetrop/Research/SU3_NF12_MCRG

set gauge_dir = \
${exec_dir}/Run_new${label}_${ns}${nt}/Configs

set output = ${home_dir}/10_0.46_0.64/mcrg_${low}_${ns}${nt}_${beta}_${mass}.${count}


set exec_file_f = $binary



date >>$output

set ncpus = `cat /proc/cpuinfo | grep -c processor`
#echo running $ncpus nodes

/usr/local/mpich2-1.4.1p1/bin/mpirun -np  $ncpus  \
$exec_file_f << EOF  >> $output
prompt 0
nx $ns
ny $ns
nz $ns
nt $nt

alpha_hyp1 0.2
alpha_hyp2 0.2
num_alpha 10
alpha_mcrg 0.46
alpha_mcrg 0.48
alpha_mcrg 0.5
alpha_mcrg 0.52
alpha_mcrg 0.54
alpha_mcrg 0.56
alpha_mcrg 0.58
alpha_mcrg 0.60
alpha_mcrg 0.62
alpha_mcrg 0.64
reload_serial ${gauge_dir}/gauge_${ns}${nt}_${beta}_${beta_a}_${mass}_${low}.${count}
EOF


date >>$output
while ( $count < $last)

        @ counter = $count + 1


csh $home_dir/do_mcrg $counter $last $beta $mass $ns $nt $low

@ count = $last + 1

end


echo Groom

# try to groom

rm ttb
ps -ef | grep anna | grep $binary | awk '{print "kill -9  ",$2}' >>ttb
sh ./ttb



exit

